### ISSUE TITLE
/restart endpoint is failing with the error "java.lang.IllegalStateException: org.springframework.context.annotation.AnnotationConfigApplicationContext has been closed already"

### ISSUE THREAD

**Issue by nandu777** [spring-projects/spring-cloud#34]
2018-11-27 14:59:43.687  INFO 9624 --- [     Thread-135] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@5980e29f: startup date [Tue Nov 27 14:56:58 IST 2018]; parent: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@bdd2027
2018-11-27 14:59:43.729  INFO 9624 --- [     Thread-135] ConfigServletWebServerApplicationContext : Closing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@bdd2027: startup date [Tue Nov 27 14:56:33 IST 2018]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@2cc3ad05
2018-11-27 14:59:43.756  INFO 9624 --- [     Thread-135] o.s.c.n.e.s.EurekaServiceRegistry        : Unregistering application xc-auth-server with eureka with status DOWN
2018-11-27 14:59:43.757  WARN 9624 --- [     Thread-135] com.netflix.discovery.DiscoveryClient    : Saw local status change event StatusChangeEvent [timestamp=1543310983757, current=DOWN, previous=UP]
2018-11-27 14:59:43.757  INFO 9624 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_XC-AUTH-SERVER/xc-auth-server: registering service...
2018-11-27 14:59:43.757  INFO 9624 --- [     Thread-135] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@2e9f5499: startup date [Tue Nov 27 14:57:06 IST 2018]; parent: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@bdd2027
2018-11-27 14:59:43.763  INFO 9624 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_XC-AUTH-SERVER/xc-auth-server - registration status: 204
2018-11-27 14:59:43.852  INFO 9624 --- [     Thread-135] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase 2147483647
2018-11-27 14:59:43.857  INFO 9624 --- [     Thread-135] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase 2147483547
2018-11-27 14:59:43.858  INFO 9624 --- [     Thread-135] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase 2147482647
2018-11-27 14:59:43.906  INFO 9624 --- [container-0-C-1] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService
2018-11-27 14:59:43.908  INFO 9624 --- [container-0-C-1] essageListenerContainer$ListenerConsumer : Consumer stopped
2018-11-27 14:59:43.909  INFO 9624 --- [     Thread-135] s.i.k.i.KafkaMessageDrivenChannelAdapter : stopped org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter@4dbeae45
2018-11-27 14:59:43.910  INFO 9624 --- [     Thread-135] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase 0
2018-11-27 14:59:43.912  INFO 9624 --- [     Thread-135] o.s.i.endpoint.EventDrivenConsumer       : Removing {logging-channel-adapter:_org.springframework.integration.errorLogger} as a subscriber to the 'errorChannel' channel
2018-11-27 14:59:43.913  INFO 9624 --- [     Thread-135] o.s.i.channel.PublishSubscribeChannel    : Channel 'xc-auth-server-1.errorChannel' has 0 subscriber(s).
2018-11-27 14:59:43.914  INFO 9624 --- [     Thread-135] o.s.i.endpoint.EventDrivenConsumer       : stopped _org.springframework.integration.errorLogger
2018-11-27 14:59:43.915  INFO 9624 --- [     Thread-135] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase -2147482648
2018-11-27 14:59:43.962  INFO 9624 --- [     Thread-135] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
2018-11-27 14:59:43.965  INFO 9624 --- [     Thread-135] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans
2018-11-27 14:59:44.258  INFO 9624 --- [     Thread-135] s.c.a.AnnotationConfigApplicationContext : Closing FeignContext-xc-application-registry: startup date [Tue Nov 27 14:56:46 IST 2018]; parent: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@bdd2027
2018-11-27 14:59:44.377  INFO 9624 --- [     Thread-135] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService 'taskScheduler'
2018-11-27 14:59:44.417  INFO 9624 --- [     Thread-135] com.netflix.discovery.DiscoveryClient    : Shutting down DiscoveryClient ...
2018-11-27 14:59:47.420  INFO 9624 --- [     Thread-135] com.netflix.discovery.DiscoveryClient    : Unregistering ...
2018-11-27 14:59:47.435  INFO 9624 --- [     Thread-135] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_XC-AUTH-SERVER/xc-auth-server - deregister  status: 200
2018-11-27 14:59:47.718  INFO 9624 --- [     Thread-135] com.netflix.discovery.DiscoveryClient    : Completed shut down of DiscoveryClient
2018-11-27 14:59:47.730  INFO 9624 --- [     Thread-135] o.s.i.monitor.IntegrationMBeanExporter   : Unregistering JMX-exposed beans on shutdown
2018-11-27 14:59:47.732  INFO 9624 --- [     Thread-135] o.s.i.monitor.IntegrationMBeanExporter   : Unregistering JMX-exposed beans
2018-11-27 14:59:47.733  INFO 9624 --- [     Thread-135] o.s.i.monitor.IntegrationMBeanExporter   : Summary on shutdown: nullChannel
2018-11-27 14:59:47.733  INFO 9624 --- [     Thread-135] o.s.i.monitor.IntegrationMBeanExporter   : Summary on shutdown: apikeys-channel-writable
2018-11-27 14:59:47.733  INFO 9624 --- [     Thread-135] o.s.i.monitor.IntegrationMBeanExporter   : Summary on shutdown: errorChannel
2018-11-27 14:59:47.734  INFO 9624 --- [     Thread-135] o.s.i.monitor.IntegrationMBeanExporter   : Summary on shutdown: apikeys-channel-readable
2018-11-27 14:59:47.734  INFO 9624 --- [     Thread-135] o.s.i.monitor.IntegrationMBeanExporter   : Summary on shutdown: org.springframework.cloud.stream.binding.StreamListenerMessageHandler@35d145fb
2018-11-27 14:59:47.736  INFO 9624 --- [     Thread-135] o.s.i.monitor.IntegrationMBeanExporter   : Summary on shutdown: _org.springframework.integration.errorLogger.handler
2018-11-27 14:59:48.413  INFO 9624 --- [     Thread-135] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2018-11-27 14:59:48.425  INFO 9624 --- [ost-startStop-2] o.apache.catalina.core.StandardWrapper   : Waiting for [1] instance(s) to be deallocated for Servlet [dispatcherServlet]
2018-11-27 14:59:49.428  INFO 9624 --- [ost-startStop-2] o.apache.catalina.core.StandardWrapper   : Waiting for [1] instance(s) to be deallocated for Servlet [dispatcherServlet]
2018-11-27 14:59:50.433  INFO 9624 --- [ost-startStop-2] o.apache.catalina.core.StandardWrapper   : Waiting for [1] instance(s) to be deallocated for Servlet [dispatcherServlet]
2018-11-27 14:59:50.533  INFO 9624 --- [ost-startStop-2] o.a.c.c.C.[Tomcat].[localhost].[/]       : Destroying Spring FrameworkServlet 'dispatcherServlet'
2018-11-27 14:59:50.551  INFO 9624 --- [     Thread-135] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@2cc3ad05: startup date [Tue Nov 27 14:56:24 IST 2018]; root of context hierarchy
2018-11-27 14:59:50.562  INFO 9624 --- [     Thread-135] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService
2018-11-27 15:00:12.706 ERROR 9624 --- [     Thread-135] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: org.springframework.context.annotation.AnnotationConfigApplicationContext@2cc3ad05 has been closed already
	at org.springframework.context.support.AbstractApplicationContext.assertBeanFactoryActive(AbstractApplicationContext.java:1073) ~[spring-context-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBeanNamesForType(AbstractApplicationContext.java:1185) ~[spring-context-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.getOrderedBeansOfType(BootstrapApplicationListener.java:329) ~[spring-cloud-context-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.apply(BootstrapApplicationListener.java:303) ~[spring-cloud-context-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:107) ~[spring-cloud-context-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:70) ~[spring-cloud-context-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127) ~[spring-context-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:74) ~[spring-boot-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54) ~[spring-boot-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:364) ~[spring-boot-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:323) ~[spring-boot-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.cloud.context.restart.RestartEndpoint.doRestart(RestartEndpoint.java:160) [spring-cloud-context-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.cloud.context.restart.RestartEndpoint.safeRestart(RestartEndpoint.java:99) [spring-cloud-context-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]

2018-11-27 15:00:14.677  INFO 9624 --- [     Thread-135] o.s.c.context.restart.RestartEndpoint    : Could not doRestart: org.springframework.context.annotation.AnnotationConfigApplicationContext@2cc3ad05 has been closed already

**Comment by spencergibb** [comment]
Please don't post multiple times.

Closing in favor of https://github.com/spring-cloud/spring-cloud-config/issues/1204
