### ISSUE TITLE
BootstrapApplicationListener.CloseContextOnFailureApplicationListener missing method implementation

### ISSUE THREAD

**Issue by gsbtech** [spring-projects/spring-cloud#54]
Using 
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
            <version>2.1.1.RELEASE</version>

            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-context</artifactId>
           <version>2.1.1.RELEASE</version>

does not work with  spring.boot 4.3.18+ or 5.x
because class org.springframework.cloud.bootstrap.BootstrapApplicationListener.CloseContextOnFailureApplicationListener does not implement method SmartApplicationListener.supportsSourceType()

My spring boot application cannot start.

Error:
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-Apr-16 16:54:23.591Z level=ERROR thread=main pid=84562 code_location=o.s.boot.SpringApplication                Application run failed
java.lang.AbstractMethodError: null
	at org.springframework.core.OrderComparator.findOrder(OrderComparator.java:142)
	at org.springframework.core.annotation.AnnotationAwareOrderComparator.findOrder(AnnotationAwareOrderComparator.java:65)
	at org.springframework.core.OrderComparator.getOrder(OrderComparator.java:125)
	at org.springframework.core.OrderComparator.getOrder(OrderComparator.java:113)
	at org.springframework.core.OrderComparator.doCompare(OrderComparator.java:82)
	at org.springframework.core.OrderComparator.compare(OrderComparator.java:68)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:360)
	at java.util.TimSort.sort(TimSort.java:220)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1462)
	at org.springframework.boot.SpringApplication.asUnmodifiableOrderedSet(SpringApplication.java:1325)
	at org.springframework.boot.SpringApplication.getListeners(SpringApplication.java:1234)
	at org.springframework.boot.context.event.EventPublishingRunListener.contextLoaded(EventPublishingRunListener.java:85)
	at org.springframework.boot.SpringApplicationRunListeners.contextLoaded(SpringApplicationRunListeners.java:66)
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:394)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:328)
	at com.xoom.inf.boot.api.autoconf.XoomBootApplication.run(XoomBootApplication.java:70)
	at com.xoom.platform.trust.Application.runApplication(Application.java:112)
	at com.xoom.platform.trust.Application.main(Application.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)

**Comment by spencergibb** [comment]
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

This should go in https://github.com/spring-cloud/spring-cloud-commons/issues

It looks like you have an incompatible version of spring boot. Spring Cloud Greenwich.X is only compatible with boot 2.1.x and framework 5.1.x

**Comment by gsbtech** [comment]
Thank you.  I think the spring boot might not have anything to do.

As mentioned in the message, it is the class in spring cloud context that fails to implement the SmartApplicationListener method  supportsSourceType()
I am using the latest spring cloud  release (2.1.1.RELEASE).

Current spring 5.1.6,  org.springframework.context.event.SmartApplicationListener
still shows the method in question.
https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/context/event/SmartApplicationListener.html
